name: pobre_simulator
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  sqflite: ^2.3.3+1
  path: ^1.9.0
  flutter_lints: ^5.0.0
  google_fonts: ^6.2.1
  mask_text_input_formatter: ^2.9.0
  intl: ^0.19.0
  flutter_iconpicker: ^4.0.1
  flutter_colorpicker: ^1.1.0
  dropdown_button2: ^2.3.9
  provider: ^6.1.2
  path_provider: ^2.1.5
  flutter_slidable: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.1.1


flutter:

  uses-material-design: true
